# Generated by Django 5.2.1 on 2025-05-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('other', 'Other')], default='bug', max_length=20),
        ),
    ]
